task_id: my_task1
click_field: click
weight_field:
min_shows: 5

create_feature_map: false
create_feature_stats: true

pipeline:
  - action__preprocess
  - action__compute_feature_stats
  - action__compute_feature_map
  - action__prepare_log_for_vw
  - action__learn_vw
  - action__apply_vw
  - action__compute_metrics
  - action__save_message_bus

learn:
  namespaces:
    - ad_id
  quadratic:
    - [ad_id, document_id]
  cubic:

  ns_rename:
    ad_id: ad_id
    document_id: document_id

  learn_file:

  vw:
    binary: vw
    num_bits: 25
    loss: logistic
    passes: 300
    l2:
    l1:
    learn_method: "--bfgs"
    manual_bias: false
    learn_options: "--holdout_off --termination 0.0"
    hashing_mode: auto

  crr:
    group_key: display_id
    active: false
    crr_alpha: 0.9

test:
  test_file:

metrics:
  class_field: clicked
  predictions_field: sigmoid_vw
  group_field: display_id
